### ISSUE TITLE
Exibir progresso do download

### ISSUE THREAD

**Issue by hitalos** [suissa/pleaseGetSomeMusicForMe#21]
Exibir informações sobre o download (ao menos tamanho total e o quanto já foi baixado).

**Comment by suissa** [comment]
https://www.npmjs.com/package/httpinvoke

**Comment by suissa** [comment]
MTO OLD: https://www.npmjs.com/package/download-progress

Mas dá [arapegar a ideia https://github.com/AYapejian/download-progress/blob/master/lib/download-progress.js

**Comment by suissa** [comment]
Niceee: https://github.com/substack/node-charm
