### ISSUE TITLE
Criar pasta quando a mesma nao existir

### ISSUE THREAD

**Issue by suissa** [suissa/pleaseGetSomeMusicForMe#5]
Estamos definindo ocmo padrão a pasta home/Music/download como padrao, entao caso nao tenha precisamos criar.

**Fazer essa verificação no INICIO do script**

**Comment by diguinhorocks** [comment]
sugestão: criar uma question no Inquirer para que o usuário também possa informar a pasta que deseja, mantendo a padrão ja selecionada caso não escolha nada.
