### ISSUE TITLE
Adicionar outras APIs para buscar a musica

### ISSUE THREAD

**Issue by suissa** [suissa/pleaseGetSomeMusicForMe#7]
Adicionar busca via YOUTUBE onde pegue o link do video e jogue em https://www.youtubeinmp3.com/pt/download/?video=LINK

E baixe a musica dando um GET no href do a#download 

Exemplo:

```html
<a target="_blank" class="button fullWidth" id="download" href="/download/get/?i=iPjWsU1xBPAg71TEg5b%2FwCp4wD1dWyPbXHJnCAX3NhzbpJZJGiv%2FZhw4uuqLEdRtaFRH%2BkzPNwCKizFVFYRlnw%3D%3D"><i class="fa fa-cloud-download"></i> Baixar MP3</a>
```

**Comment by diguinhorocks** [comment]
[essa branch aqui](https://github.com/suissa/pleaseGetSomeMusicForMe/tree/multiple-provider-search) deu um jeito nessa parada
